### ISSUE TITLE
FileNotFound on library

### ISSUE THREAD

**Issue by nektro** [jecolon/ziglyph#13]
https://github.com/jecolon/ziglyph/commit/384fd04408e4ada6540e014249127a52ec001ffc changed the casing of the packages entry point from `src/Ziglyph.zig` to `src/ziglyph.zig` however the file in source is still uppercase. trying to build a project now fails.

**Comment by jecolon** [comment]
This must be some weird git behavior that's new to me. I had to run `git mv` on the file to actually get it to rename. The normal `mv` command was just being ignored. I think it's fixed now. Thanks for the heads up!

**Comment by nektro** [comment]
confirmed fixed with https://github.com/jecolon/ziglyph/commit/c37d93b6c8e6a65aaf7f76157a8a95f9c9c43f61

**Comment by nektro** [comment]
thanks :)
