### ISSUE TITLE
cross validation and comparison (to libgrapheme)

### ISSUE THREAD

**Issue by matu3ba** [jecolon/ziglyph#14]
https://git.suckless.org/libgrapheme/file/README.html

Probably you also want to explain when to use which of your libraries?
Its not immediately clear from the description what stuff is for grapheme, glyph, codepoints and code units.
https://stackoverflow.com/a/27331885

**Comment by jecolon** [comment]
@matu3ba thanks for the feedback. I added a link to the Unicode Text Processing series of articles I wrote on ZigNEWS, which pretty much covers all the background info on Unicode and usage of Ziglyph to handle Unicode text. Although I haven't looked at the source, libgrapheme seems to cover just the Grapheme Cluster handling aspect of Unicode, which in Ziglyph is handled mostly via the `GraphemeIterator` struct. On the other hand, Ziglyph has a much more comprehensive library of functions, namespaces, and structures to deal with many more parts of the Unicode standard. I'll be looking into libgrapheme more closely to see if Ziglyph can adopt any missing functionality.
