### ISSUE TITLE
Link problem under Windows in debug mode: unresolved external symbol NtClose

### ISSUE THREAD

**Issue by jlfaucher** [jecolon/ziglyph#16]
Hello
Thanks for your great work on Ziglyph!

I integrated Ziglyph in a C++ project, using a small layer cziglyph to export the functions I need.
https://github.com/jlfaucher/executor/tree/master/sandbox/jlf/trunk/interpreter/classes/support/m17n/cziglyph
https://github.com/jlfaucher/executor/blob/fe41555797b241d20cd99422e1998e6bfaf023e3/sandbox/jlf/trunk/CMakeLists.txt#L696

Works good, but I have a link problem when building in debug mode:
```
[ 62%] Linking CXX shared library bin\rexx.dll
   Creating library lib\rexx.lib and object lib\rexx.exp
cziglyph.lib(cziglyph.obj) : error LNK2019: unresolved external symbol NtClose referenced in function std.os.windows.CloseHandle
cziglyph.lib(cziglyph.obj) : error LNK2019: unresolved external symbol NtCreateFile referenced in function std.target.Arch.isWasm
cziglyph.lib(cziglyph.obj) : error LNK2019: unresolved external symbol NtLockFile referenced in function std.target.Arch.isWasm
cziglyph.lib(cziglyph.obj) : error LNK2019: unresolved external symbol NtWaitForKeyedEvent referenced in function std.meta.assumeSentinel.176
cziglyph.lib(cziglyph.obj) : error LNK2019: unresolved external symbol NtCreateKeyedEvent referenced in function std.fmt.formatValue.226
bin\rexx.dll : fatal error LNK1120: 5 unresolved externals
```
As a workaround, I build cziglyph in release mode, always, and that's fine.
I'm curious to know if I do something wrong... I have a very limited knowledge of Zig.

Could it be related to lib.bundle_compiler_rt = true ?
https://github.com/jlfaucher/executor/blob/275cb0afa1fecd312c3bc8749a5e109b215b9c60/sandbox/jlf/trunk/interpreter/classes/support/m17n/cziglyph/build.zig#L30

Jean-Louis

**Comment by jecolon** [comment]
Hi @jlfaucher ; from that error mesage you get, it seems to me that it's probably a problem external to Ziglyph, given that it lists functions such as `std.os.windows.CloseHandle` that aren't even used (at least directly) in Ziglyph. In addition, the fuctions you're using from Ziglyph basically only use `std.mem.Allocator` and `std.ArrayList` from the standard library, so it's really strange that they could produce those errors. I don't know if it has anything to do with `lib.bundle_compiler_rt = true` in build.zig but have your tried to build without it?

**Comment by jlfaucher** [comment]
Hi @jecolon 
Thanks for your feedback!
Removing `lib.bundle_compiler_rt = true` did not eliminate the link error under Windows.
Removing the dependency on libC did not either (tested with GeneralPurposeAllocator, which is 15 times slower than c_allocator for my test case).

I will stay with my workaround.
