### ISSUE TITLE
Streaming Segmenters

### ISSUE THREAD

**Issue by glyh** [jecolon/ziglyph#18]
I want to use this library to write my parser, the problem I am facing is that I don't know if the values in the current bufer is a valid utf8 string, or it's just a prefix of a valid utf8 string. 

I checked the GraphemeIterator, it checks every char in the given byte array, then it will not work if I don't have the whole string yet...
https://github.com/jecolon/ziglyph/blob/531d30951219f4703c85a51521745860185be6f2/src/segmenter/Grapheme.zig#L80
So is there any workaround? 

Or put simply, I can't make this library work well with Readers, because it expects everything to be already read.

**Comment by glyh** [comment]
OK I have an workaround in my mind right now, probably I first need a round of check to ensure I have enough bytes for CPs, and then throw it into Graphemes, but there's redundant work happening. Is it possible to make it better?

**Comment by jecolon** [comment]
Hi @glyh . Given that Grapheme Clusters are practically open-ended in the number of code points that can combine to produce a single cluster, I suspect that adapting GraphemeIterator to support streams of unknown length would require significant overhead (lookahed buffering) and memory allocation. I think the best approach would be to develop a new, separate data structure (StreamingGraphemeIterator perhaps) to handle such cases. From use cases and libraries from other languages I've studied, it seems that the most common case is the delimitted text scenario, where common delimiters like `\n`, `\r\n`, line separator, or paragraph separator are used as split points. Does yur data lack any kind of delimiter where you could split on and then process the chunks?

**Comment by glyh** [comment]
@jecolon I am trying to write a parser. But I'm trying my best to make no assumption to my input(e.g. there may be a super long line, or multiple consecutive "\n"'s making the algorithm slow). Also, treating data as ASCII in the first place may be problematic, what if the ascii code for "\n" is inside a grapheme?

**Comment by glyh** [comment]
Also, I actually think there would be more changes, because the underlying CodePointIterator is also not streaming.

**Comment by glyh** [comment]
I've checked the CodePoint class, I feel some of the field doesn't make sense for streaming. E.g. offset doesn't make sense.

Also the current CodePoint class is not doing any allocation, but I feel if it's the streaming case we have to do allocation.

If I were to create StreamingXXX for CodePoint and Grapheme, wouldn't that mean we have to maintain a different set of segmenter for any units? I feel that is awful because it's a bunch of repetitions.

**Comment by jecolon** [comment]
> what if the ascii code for "\n" is inside a grapheme?

Well-formed UTF-8 does not allow this, it's forbidden by the spec. So splitting by `\n` is always safe and deterministic.

**Comment by jecolon** [comment]
> But I'm trying my best to make no assumption to my input

Thinking on this some more, even in a streaming context, you can iterate over reading the chunks split by the delimiters using allocation to handle the unknown input size problem (i.e. `Reader.readUntilDelimiterOrEofAlloc`). And according to the spec, splitting on the common line separators will always produce well-formed UTF-8 chunks if the source input is also well-formed UTF-8. Assuming the input is well-formed UTF-8 is the bare minimum assumption you would have to make in this case, and most modern programming languages (Zig, Rust, Go) make this assumption too, so you're in good company!

**Comment by jecolon** [comment]
Just added:

```
const readCodePoint = @import("ziglyph").readCodePoint;

var buf = "abé😹".*;
var fis = std.io.fixedBufferStream(&buf);
const reader = fis.reader();

try std.testing.expectEqual(@as(u21, 'a'), (try readCodePoint(reader)).?);
try std.testing.expectEqual(@as(u21, 'b'), (try readCodePoint(reader)).?);
try std.testing.expectEqual(@as(u21, 'é'), (try readCodePoint(reader)).?);
try std.testing.expectEqual(@as(u21, '😹'), (try readCodePoint(reader)).?);
try std.testing.expectEqual(@as(?u21, null), try readCodePoint(reader));
```


```
const Grapheme = @import("ziglyph").Grapheme;
const StreamingGraphemeIterator = Grapheme.StreamingGraphemeIterator;

var buf = "abe\u{301}😹".*;
var fis = std.io.fixedBufferStream(&buf);
const reader = fis.reader();
var iter = try StreamingGraphemeIterator(@TypeOf(reader)).init(std.testing.allocator, reader);
const want = [_][]const u8{ "a", "b", "e\u{301}", "😹" };

for (want) |str| {
    const gc = (try iter.next()).?;
    defer std.testing.allocator.free(gc.bytes);
    try std.testing.expect(gc.eql(str));
}

try std.testing.expectEqual(@as(?Grapheme, null), try iter.next());
```

**Comment by glyh** [comment]
Great! Thank you!
