### ISSUE TITLE
XID_Start/XID_Continue categories?

### ISSUE THREAD

**Issue by Phytolizer** [jecolon/ziglyph#24]
Hi, just a short request. Could you please add category tests for the XID_Start and XID_Continue categories, so that I can use this library for a small lexer project I'm working on? It would be much appreciated.

It's entirely possible I'm missing something, and you already provide this.

**Comment by jecolon** [comment]
Hi @Phytolizer ; yeah it's in the `derived_core_properties` namespace:

```zig
const ziglyph = @import("ziglyph");
const dcp = ziglyph.derived_core_properties;

test "XID" {
    try std.testing.expect(dcp.isXidStart('a'));
    try std.testing.expect(!dcp.isXidStart('0'));
    try std.testing.expect(dcp.isXidContinue('0'));
    try std.testing.expect(!dcp.isXidContinue(' '));
}
```

**Comment by Phytolizer** [comment]
Oops! Sorry about that, thanks for the pointer!
